# Generated by Django 5.1.5 on 2025-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_remove_product_name_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='без названия', max_length=100),
            preserve_default=False,
        ),
    ]
